# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='following',
        ),
        migrations.AddField(
            model_name='friend',
            name='user_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.User_details'),
        ),
    ]
